# Generated by Django 3.0.7 on 2020-06-27 17:43

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='refer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
