# Generated by Django 3.0.7 on 2020-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200627_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='refer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
