# Generated by Django 3.0.7 on 2020-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20200627_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='refer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
