# Generated by Django 3.0.7 on 2020-06-28 19:33

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200628_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='refer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
